### ISSUE TITLE
Epic: Tasks for v3.8 release

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#670]
This is an Epic (overview) issue for the next release (v3.8)

~~To Be Voted On:~~
- [x] #631 - Update examples to add editing (and testing)
- [x] #636 - Reorganization of layer tools

Code issues [Milestone 3.8](https://github.com/geomoose/gm3/milestone/14) to be addressed:
- [x] #645 - Add Mapbook hash parameter
- [x] #47 - Feature Editing -  needs combobox dropdown for properties
- [x] #564 - Set Initial Extent by Bounding Box

Other Tasks:
- [x] Online Demo: add WFS-T server+database
- [x] Document Editing

**Comment by jmckenna** [comment]
Regarding online demo: I'll also setup and host the MapServer+TinyOWS GeoMoose WFS-T demo on the MS4W demo server:  https://ms4w.dev

**Comment by brentfraser** [comment]
All done.
